/// Flutter icons CustomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String _kFontPkg = null;

  static const IconData th = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award_1 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag_empty = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tags = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrench = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_outline = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stopwatch = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = IconData(0xf02d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash = IconData(0xf070, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_amount_down = IconData(0xf160, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_amount_up = IconData(0xf161, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xf1da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasklist = IconData(0xf31c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_reader = IconData(0xf5da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spell_check = IconData(0xf891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
